name = "tubelinkr"
compatibility_date = "2024-04-07"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "tubelinkr-db"
database_id = "7fd2cd09-fafa-496f-8310-a7e86ca5c03c"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "tubelinkr-db"
database_id = "7fd2cd09-fafa-496f-8310-a7e86ca5c03c"

[env.preview]
vars = { ENVIRONMENT = "preview" }

[[env.preview.d1_databases]]
binding = "DB"
database_name = "tubelinkr-db"
database_id = "7fd2cd09-fafa-496f-8310-a7e86ca5c03c"
