import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { db } from '../lib/cloudflare';
import { Layout } from '../components';

export function NewLinkPage() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [originalUrl, setOriginalUrl] = useState('');
  const [title, setTitle] = useState('');
  const [slug, setSlug] = useState('');
  const [error, setError] = useState('');
  const [slugError, setSlugError] = useState('');
  const [slugSuggestions, setSlugSuggestions] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [isSlugAutoGenerated, setIsSlugAutoGenerated] = useState(false);
  const [debouncedSlug, setDebouncedSlug] = useState('');
  const [createdLink, setCreatedLink] = useState<{ id: string; slug: string } | null>(null);
  const [copiedLink, setCopiedLink] = useState<string | null>(null);

  const sanitizeSlug = (value: string): string => {
    return value
      .toLowerCase()
      .replace(/[^a-z0-9-\s]/g, '')
      .replace(/\s+/g, '-')
      .replace(/--+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 50);
  };

  const generateSlugFromTitle = (titleText: string): string => {
    return sanitizeSlug(titleText);
  };

  const validateSlug = (value: string): { valid: boolean; error: string } => {
    if (!value) {
      return { valid: true, error: '' };
    }
    if (value.length < 3) {
      return { valid: false, error: 'Too short (min 3 characters)' };
    }
    if (value.length > 50) {
      return { valid: false, error: 'Too long (max 50 characters)' };
    }
    if (!/^[a-z0-9-]+$/.test(value)) {
      return { valid: false, error: 'Invalid characters (use a-z, 0-9, hyphens only)' };
    }
    if (/^-/.test(value) || /-$/.test(value)) {
      return { valid: false, error: 'Cannot start or end with hyphen' };
    }
    return { valid: true, error: '' };
  };

  const generateSlugSuggestions = (baseSlug: string): string[] => {
    const suggestions = [
      `${baseSlug}-1`,
      `${baseSlug}-deal`,
      `${baseSlug}-yt`,
      `${baseSlug}-link`,
      `${baseSlug}-2026`
    ];
    return suggestions.slice(0, 3);
  };

  const checkSlugAvailability = async (value: string) => {
    if (!value || !user) {
      setSlugSuggestions([]);
      return;
    }
    
    const validation = validateSlug(value);
    if (!validation.valid) {
      setSlugError(validation.error);
      setSlugSuggestions([]);
      return;
    }
    
    setSlugError('');
    
    try {
      const existingLinks = await db.getLinksByUserId(user.id);
      const existingLink = existingLinks.find((l) => l.slug === value);
      
      if (existingLink) {
        setSlugError('Slug already exists');
        setSlugSuggestions(generateSlugSuggestions(value));
      } else {
        setSlugSuggestions([]);
      }
    } catch (err) {
      console.error('Error checking slug availability:', err);
    }
  };

  const handleSlugChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const sanitized = sanitizeSlug(e.target.value);
    setSlug(sanitized);
    setIsSlugAutoGenerated(false);
    
    const validation = validateSlug(sanitized);
    if (!validation.valid) {
      setSlugError(validation.error);
    } else {
      setSlugError('');
    }
  };

  const handleTitleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newTitle = e.target.value;
    setTitle(newTitle);
    
    if (newTitle && !isSlugAutoGenerated) {
      const generatedSlug = generateSlugFromTitle(newTitle);
      setSlug(generatedSlug);
      setIsSlugAutoGenerated(true);
    }
  };

  const selectSlugSuggestion = (suggestion: string) => {
    setSlug(suggestion);
    setSlugError('');
    setSlugSuggestions([]);
  };

  const copyToClipboard = (linkKey: string, url: string) => {
    navigator.clipboard.writeText(url);
    setCopiedLink(linkKey);
    setTimeout(() => setCopiedLink(null), 2000);
  };

  // Debounced slug availability check
  useEffect(() => {
    const timer = setTimeout(() => {
      setDebouncedSlug(slug);
    }, 500);

    return () => clearTimeout(timer);
  }, [slug]);

  useEffect(() => {
    if (debouncedSlug && !isSlugAutoGenerated) {
      checkSlugAvailability(debouncedSlug);
    }
  }, [debouncedSlug, isSlugAutoGenerated]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (!originalUrl) {
      setError('Original URL is required');
      return;
    }

    try {
      new URL(originalUrl);
    } catch {
      setError('Please enter a valid URL');
      return;
    }

    let finalSlug = slug;
    if (!finalSlug && title) {
      finalSlug = generateSlugFromTitle(title);
    }

    if (!finalSlug) {
      setError('Please provide a title or custom slug');
      return;
    }

    const validation = validateSlug(finalSlug);
    if (!validation.valid) {
      setError(validation.error);
      return;
    }

    setLoading(true);

    try {
      if (!user) {
        setError('User not authenticated');
        return;
      }

      const existingLinks = await db.getLinksByUserId(user.id);
      const existingLink = existingLinks.find((l) => l.slug === finalSlug);

      if (existingLink) {
        setError('A link with this slug already exists');
        setLoading(false);
        return;
      }

      const newLink = await db.createLink({
        user_id: user.id,
        slug: finalSlug,
        original_url: originalUrl,
        title: title || undefined,
      });

      setCreatedLink({ id: newLink.id, slug: finalSlug });
    } catch (error: any) {
      setError(error.message || 'Failed to create link');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Layout>
      <div className="max-w-2xl mx-auto px-4 py-8 sm:px-6 lg:px-8 overflow-x-hidden">
        {createdLink ? (
          <div className="space-y-6">
            <div className="mb-8">
              <h1 className="text-2xl sm:text-3xl font-bold text-white">Link Created!</h1>
              <p className="text-gray-400 mt-2">Your link is ready to use</p>
            </div>

            <div className="bg-gray-900 border border-gray-800 rounded-lg p-6 space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  Tracking Link (Internal)
                </label>
                <div className="flex items-center gap-2">
                  <div className="flex-1 min-w-0 px-4 py-3 bg-gray-950 border border-gray-800 rounded-lg text-sm text-gray-400 font-mono break-all">
                    {window.location.origin}/api/redirect/{createdLink.id}/{createdLink.slug}?source=d
                  </div>
                  <button
                    onClick={() => copyToClipboard('tracking', `${window.location.origin}/api/redirect/${createdLink.id}/${createdLink.slug}?source=d`)}
                    className="px-4 py-3 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-lg transition-colors flex-shrink-0"
                  >
                    {copiedLink === 'tracking' ? 'Copied!' : 'Copy'}
                  </button>
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  Public Link (Live)
                </label>
                <div className="flex items-center gap-2">
                  <div className="flex-1 min-w-0 px-4 py-3 bg-gray-950 border border-gray-800 rounded-lg text-sm text-gray-400 font-mono break-all">
                    https://go.tubelinkr.com/{user?.username}/{createdLink.slug}
                  </div>
                  <button
                    onClick={() => copyToClipboard('public', `https://go.tubelinkr.com/${user?.username}/${createdLink.slug}`)}
                    className="px-4 py-3 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-lg transition-colors flex-shrink-0"
                  >
                    {copiedLink === 'public' ? 'Copied!' : 'Copy'}
                  </button>
                </div>
                <p className="mt-2 text-xs text-gray-500">
                  Share this branded URL anywhere
                </p>
              </div>
            </div>

            <div className="flex flex-col sm:flex-row gap-4">
              <button
                onClick={() => navigate('/links')}
                className="flex-1 px-6 py-3 bg-gray-800 hover:bg-gray-700 text-white font-medium rounded-lg transition-colors"
              >
                View All Links
              </button>
              <button
                onClick={() => {
                  setCreatedLink(null);
                  setOriginalUrl('');
                  setTitle('');
                  setSlug('');
                  setSlugError('');
                }}
                className="flex-1 px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-lg transition-colors"
              >
                Create Another Link
              </button>
            </div>
          </div>
        ) : (
          <div className="space-y-6">
            <div className="mb-8">
              <h1 className="text-2xl sm:text-3xl font-bold text-white">Create New Link</h1>
              <p className="text-gray-400 mt-2">Turn any link into a clean, trackable link you can use across your content</p>
            </div>

            <form onSubmit={handleSubmit} className="space-y-6">
          <div>
            <label htmlFor="originalUrl" className="block text-sm font-medium text-gray-300 mb-2">
              Original URL *
            </label>
            <input
              type="url"
              id="originalUrl"
              value={originalUrl}
              onChange={(e) => setOriginalUrl(e.target.value)}
              placeholder="https://example.com/very/long/url?with=parameters&more=stuff"
              className="w-full px-4 py-3 bg-gray-900 border border-gray-800 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              required
            />
          </div>

          <div>
            <label htmlFor="title" className="block text-sm font-medium text-gray-300 mb-2">
              Title (optional)
            </label>
            <input
              type="text"
              id="title"
              value={title}
              onChange={handleTitleChange}
              placeholder="My Awesome Link"
              className="w-full px-4 py-3 bg-gray-900 border border-gray-800 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
            <p className="mt-2 text-xs text-gray-500">
              Slug will auto-generate from title
            </p>
          </div>

          <div>
            <label htmlFor="slug" className="block text-sm font-medium text-gray-300 mb-2">
              Custom Slug (optional)
            </label>
            <div className="flex flex-col sm:flex-row sm:items-center gap-2">
              <div className="flex flex-1">
                <div className="inline-flex items-center px-2 sm:px-3 bg-gray-800 border border-r-0 border-gray-700 rounded-l-lg text-gray-400 text-xs sm:text-sm whitespace-nowrap">
                  {window.location.host}/{user?.username}/
                </div>
                <input
                  type="text"
                  id="slug"
                  value={slug}
                  onChange={handleSlugChange}
                  placeholder="my-link"
                  className={`flex-1 min-w-0 px-3 sm:px-4 py-3 bg-gray-900 border rounded-r-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:border-transparent ${
                    slugError ? 'border-red-500 focus:ring-red-500' : 'border-gray-800 focus:ring-blue-500'
                  }`}
                />
              </div>
            </div>
            {slugError && (
              <p className="mt-2 text-xs text-red-400">{slugError}</p>
            )}
            {slugSuggestions.length > 0 && (
              <div className="mt-2">
                <p className="text-xs text-gray-500 mb-1">Suggestions:</p>
                <div className="flex flex-wrap gap-2">
                  {slugSuggestions.map((suggestion) => (
                    <button
                      key={suggestion}
                      type="button"
                      onClick={() => selectSlugSuggestion(suggestion)}
                      className="px-3 py-1 text-xs bg-gray-800 hover:bg-gray-700 text-blue-400 rounded transition-colors"
                    >
                      {suggestion}
                    </button>
                  ))}
                </div>
              </div>
            )}
            <p className="mt-2 text-xs text-gray-500">
              This is the part of your link people will see
            </p>
            <p className="mt-1 text-xs text-gray-500">
              Only lowercase letters, numbers, and hyphens allowed. 3–50 characters.
            </p>
          </div>

          {error && (
            <div className="bg-red-900/20 border border-red-800 rounded-lg p-4">
              <p className="text-red-400">{error}</p>
            </div>
          )}

          <div className="flex flex-col sm:flex-row gap-4">
            <button
              type="button"
              onClick={() => navigate('/links')}
              className="flex-1 px-6 py-3 bg-gray-800 hover:bg-gray-700 text-white font-medium rounded-lg transition-colors"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading}
              className="flex-1 px-6 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-blue-800 disabled:cursor-not-allowed text-white font-medium rounded-lg transition-colors"
            >
              {loading ? 'Creating...' : 'Create Link'}
            </button>
          </div>
        </form>
          </div>
        )}
      </div>
    </Layout>
  );
}
